name: 1.0$(rev:.r)

trigger:
- master

parameters:
  - name: RestoreBuildProjects
    type: string
    default: '**/*.csproj'
  - name: TestProjects
    type: string
    default: '**/*[Tt]ests/*.csproj'

variables:
- template: variable-set-two.yml
  # buildConfiguration: 'Release'
  # kamtest: 'default-kam'

stages:
  - stage: 'Build'
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
      - job: 'Build'
        steps:
        - script: |
            echo ${{ parameters.RestoreBuildProjects }}
            ls -R
            echo 'var => ${{ variables.kamtest }}'
          displayName: 'Run a multi-line script -> ${{ variables.kamtest }}'
        - task: DotNetCoreCLI@2
          displayName: Restore
          inputs:
            command: restore
            projects: ${{ parameters.RestoreBuildProjects }}
  
        - task: DotNetCoreCLI@2
          displayName: Build
          inputs:
            projects: ${{ parameters.RestoreBuildProjects }}
            arguments: '--configuration $(BuildConfiguration)'
  
        - task: DotNetCoreCLI@2
          displayName: Test
          inputs:
            command: test
            projects: ${{ parameters.TestProjects }}
            arguments: '--configuration $(BuildConfiguration)'


