version: '3.7'
services:

  mywebapi:
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   - NUGET_UID
      #   - NUGET_PWD
    image: sample/mywebapi
    container_name: mywebapi
    network_mode: host
    restart: "no"
    ports:
      - 5000:5000
    # healthcheck:
    #   test: curl --fail -s http://localhost:5000/index.html || exit 1
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s
    # volumes:
    #    - type: bind
    #      source: ./override
    #      target: /app/override
    environment:
    - ASPNETCORE_URLS=http://+:5000
    - DOTNET_USE_POLLING_FILE_WATCHER=true
    - ASPNETCORE_ENVIRONMENT=Development
    - DOCKER_IMAGE_VERSION=local image

  myredoc:
    image: redocly/redoc
    container_name: myredoc
    network_mode: host
    restart: "no"
    # ports are ignored when we set the network to host
    ports:
      - 8080:8081
    environment:
      - SPEC_URL2=http://localhost:5000/swagger/v1/swagger.json
      - SPEC_URL3=https://kam-redoc.azurewebsites.net/swagger/v1/swagger.json
      - SPEC_URL1=https://petstore3.swagger.io/api/v3/openapi.json
      - SPEC_URL=https://kam-redoc.azurewebsites.net/swagger/v1/swagger.yaml
 